tasks:
  - init: npm install
    command: npm run build && npm test && npx func start
ports:
  - port: 7071
    onOpen: open-preview
vscode:
  extensions:
    - Orta.vscode-jest@3.2.0:adbRMTNfxv/Rzc4SOP/c3g==